server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rs_ecommerce
    username: root
    password: root
    tomcat:
      max-wait: 20000
      max-idle: 20
      min-idle: 15
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
management:
  server:
    port: 8093
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

